export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    name: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "#fcf1ed",
  },
  {
    id: 2,
    img: "https://i.ibb.co/cXFnLLV/3.png",
    name: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "#fbf0f4",
  },
  {
    id: 3,
    img: "https://preview.colorlib.com/theme/estore/assets/img/hero/xhero_man.png.pagespeed.ic.cN86RxAvqq.webp",
    name: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "#f0f9ff",
  },
];
export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    name: "SHIRT STYLE!",
    cat: "woman",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    name: "LOUNGEWEAR LOVE",
    cat: "coats",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    name: "LIGHT JACKETS",
    cat: "jeans",
  },
];
export const popularProducts = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
  },
  {
    id: 2,
    img: "https://cdn.shopify.com/s/files/1/0101/4832/products/Angela_Natural_Tee.png?v=1606780388",
  },
  {
    id: 3,
    img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
  },
  {
    id: 4,
    img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
  },
  {
    id: 5,
    img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
  },
  {
    id: 6,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
  },
  {
    id: 7,
    img: "http://themes.smartythemes.com/swagger/wp-content/uploads/sites/layer-1.png",
  },
  {
    id: 8,
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
  },
];
export const products = [
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 1,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    img: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 2,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    img: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 3,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    img: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 4,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    img: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 5,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    img: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 6,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    image: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 7,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    image: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
  {
    name: "Herman Coat",
    desc: "Lorem Ipsum is simply dummy text of the printing and ...",
    id: 8,
    price: 89,
    color: "Yellow",
    // offPrice: 120,
    // discount: 0,
    size: [{ 0: "S" }, { 1: "M" }, { 2: "L" }],
    image: "https://i.ibb.co/YZC6n90/coat1.png",
    inStock: true,
  },
];
